1691616348819	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1691620803473	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1691620803474	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1691620803478	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1691620803480	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1691620804721	Sync.SyncScheduler	DEBUG	Woke from sleep.
1691620804721	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1691620804721	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1691620804722	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1691620806788	Sync.Service	DEBUG	User-Agent: Firefox/116.0 (Linux x86_64) FxSync/1.118.0.20230727152340.desktop
1691620806788	Sync.Service	INFO	Starting sync at 2023-08-09 23:40:06 in browser session xGHI6dgmx9M6
1691620806788	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1691620806797	Sync.Status	INFO	Resetting Status.
1691620806797	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1691620806798	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1691620806798	FirefoxAccounts	DEBUG	getOAuthToken enter
1691620806798	FirefoxAccounts	TRACE	getCachedToken returning cached token
1691620806798	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1691620806799	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1691620806799	Sync.SyncAuthManager	INFO	Getting sync key
1691620806800	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1691620806800	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1691620806800	FirefoxAccounts	DEBUG	getOAuthToken enter
1691620806800	FirefoxAccounts	TRACE	getCachedToken returning cached token
1691620806800	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1691620806800	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1691620806801	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1691620806803	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1691620806804	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1691620806804	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1691620806805	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1691620806805	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1691620806805	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1691620806806	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1691620806807	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1691620806815	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/190893309/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1691620806815	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1691620806815	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1691620806815	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1691620806816	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1691620806817	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1691620806827	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
